[package]
name = "cct"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["serde_derive"] }
serde_json = "1.0.128"
