[package]
name = "parallel-read"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
utils = { path = "../utils" }

[dev-dependencies]
baseline = { path = "../baseline" }
